CREATE EXTENSION IF NOT EXISTS pg_trgm;

create table "authorization_consents" (authorities varchar(1000), "client_id" varchar(255), principal_name varchar(255) not null, registered_client_id varchar(255) not null, primary key (principal_name, registered_client_id));
create table "authorizations" (access_token_expires_at timestamp(6) with time zone, access_token_issued_at timestamp(6) with time zone, authorization_code_expires_at timestamp(6) with time zone, authorization_code_issued_at timestamp(6) with time zone, device_code_expires_at timestamp(6) with time zone, device_code_issued_at timestamp(6) with time zone, oidc_id_token_expires_at timestamp(6) with time zone, oidc_id_token_issued_at timestamp(6) with time zone, refresh_token_expires_at timestamp(6) with time zone, refresh_token_issued_at timestamp(6) with time zone, user_code_expires_at timestamp(6) with time zone, user_code_issued_at timestamp(6) with time zone, state varchar(500), access_token_scopes varchar(1000), authorized_scopes varchar(1000), access_token_metadata varchar(2000), device_code_metadata varchar(2000), oidc_id_token_claims varchar(2000), oidc_id_token_metadata varchar(2000), refresh_token_metadata varchar(2000), user_code_metadata varchar(2000), access_token_value varchar(4000), attributes varchar(4000), authorization_code_value varchar(4000), device_code_value varchar(4000), oidc_id_token_value varchar(4000), refresh_token_value varchar(4000), user_code_value varchar(4000), access_token_type varchar(255), authorization_code_metadata varchar(255), authorization_grant_type varchar(255), "client_id" varchar(255), id varchar(255) not null, principal_name varchar(255), primary key (id));
create table "clients" (client_id_issued_at timestamp(6) with time zone, client_secret_expires_at timestamp(6) with time zone, authorization_grant_types varchar(1000), client_authentication_methods varchar(1000), post_logout_redirect_uris varchar(1000), redirect_uris varchar(1000), scopes varchar(1000), client_settings varchar(2000), token_settings varchar(2000), client_id varchar(255) unique, client_name varchar(255), client_secret varchar(255), id varchar(255) not null, primary key (id));
create table password_reset_tokens (deleted boolean not null, email_sent boolean not null, created_at timestamp(6), expires_at timestamp(6), created_by uuid, id uuid not null, "user_id" uuid, token varchar(255), primary key (id));
comment on column password_reset_tokens.deleted is 'Soft-delete indicator';
create table privilege (deleted boolean not null, created_at timestamp(6), created_by uuid, id uuid not null, name varchar(255) not null unique, primary key (id));
comment on column privilege.deleted is 'Soft-delete indicator';
create table user_connected_accounts (deleted boolean not null, connected_at timestamp(6), created_at timestamp(6), created_by uuid, id uuid not null, user_id uuid, provider varchar(255), provider_id varchar(255), primary key (id));
comment on column user_connected_accounts.deleted is 'Soft-delete indicator';
create table uploaded_file (deleted boolean not null, created_at timestamp(6), size bigint, uploaded_at timestamp(6), created_by uuid, id uuid not null, "user_id" uuid, extension varchar(255), original_file_name varchar(255), url varchar(255), primary key (id));
comment on column uploaded_file.deleted is 'Soft-delete indicator';
create table user_links (user_id uuid not null, type varchar(50) not null check ((type in ('WEBSITE','INSTAGRAM','FACEBOOK','TWITTER','LINKEDIN','YOUTUBE','TIKTOK'))), url varchar(2048) not null, primary key (user_id, type, url));
create table user_privileges (privilege_id uuid not null, user_id uuid not null, primary key (privilege_id, user_id));
create table "users" (deleted boolean not null, verified boolean, created_at timestamp(6), created_by uuid, id uuid not null, email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), profile_image_url varchar(255), role varchar(255) check ((role in ('USER','ADMIN'))), primary key (id));
comment on column "users".deleted is 'Soft-delete indicator';
create table verification_codes (deleted boolean not null, email_sent boolean not null, created_at timestamp(6), created_by uuid, id uuid not null, "user_id" uuid unique, code varchar(255), primary key (id));
comment on column verification_codes.deleted is 'Soft-delete indicator';
alter table if exists "authorization_consents" add constraint FK7u3rrcx79xyss37m2551mpx2p foreign key ("client_id") references "clients";
alter table if exists "authorizations" add constraint FK4ehcr3h1eun20h36is62nal65 foreign key ("client_id") references "clients";
alter table if exists password_reset_tokens add constraint FKrjxrqd0dudi212f0469dojcod foreign key ("user_id") references "users";
alter table if exists uploaded_file add constraint FKqhosch3tnq7i2it0mea57ts4m foreign key ("user_id") references "users";
alter table if exists user_connected_accounts add constraint FKnnce63ye8wbmdskoeco5ku43d foreign key (user_id) references "users";
alter table if exists user_links add constraint FK4wc3hhebo87m149hnxkxxmfvm foreign key (user_id) references "users";
alter table if exists user_privileges add constraint FK6rrv8daxxrco69tdpfu3a29le foreign key (privilege_id) references privilege;
alter table if exists user_privileges add constraint FKobuc3eaoytxqaj534be5b7xqs foreign key (user_id) references "users";
alter table if exists verification_codes add constraint FK2c664upaiv1f6h7e5ueyy1ae3 foreign key ("user_id") references "users";

create table comment_likes (liked_at timestamp(6), comment_id uuid not null, user_id uuid not null, primary key (comment_id, user_id));
create table comments (deleted boolean not null, created_at timestamp(6), author_user_id uuid not null, created_by uuid, id uuid not null, parent_id uuid, post_id uuid, target_id uuid not null, body varchar(4000) not null, primary key (id));
comment on column comments.deleted is 'Soft-delete indicator';
create table post_likes (liked_at timestamp(6), post_id uuid not null, user_id uuid not null, primary key (post_id, user_id));
create table post_media (deleted boolean not null, sort_order integer not null, created_at timestamp(6), created_by uuid, id uuid not null, media_type varchar(16) not null check ((media_type in ('IMAGE','VIDEO'))), post_id uuid not null, object_key varchar(1024) not null, primary key (id));
comment on column post_media.deleted is 'Soft-delete indicator';
create table posts (deleted boolean not null, is_featured boolean not null, is_pinned boolean not null, created_at timestamp(6), author_user_id uuid not null, created_by uuid, id uuid not null, target_id uuid not null, body varchar(4000), primary key (id));
comment on column posts.deleted is 'Soft-delete indicator';
create table tags (deleted boolean not null, created_at timestamp(6), created_by uuid, id uuid not null, name varchar(255) not null unique, primary key (id));
comment on column tags.deleted is 'Soft-delete indicator';
alter table if exists comment_likes add constraint FK3wa5u7bs1p1o9hmavtgdgk1go foreign key (comment_id) references comments;
alter table if exists comments add constraint FKlri30okf66phtcgbe5pok7cc0 foreign key (parent_id) references comments;
alter table if exists post_likes add constraint FKa5wxsgl4doibhbed9gm7ikie2 foreign key (post_id) references posts;
alter table if exists post_media add constraint FK1urcum9dtf0vgul7k405f4r2d foreign key (post_id) references posts;

create table interest_group (deleted boolean not null, created_at timestamp(6), created_by uuid, id uuid not null, description varchar(255) not null, name varchar(255) not null, primary key (id));
comment on column interest_group.deleted is 'Soft-delete indicator';
create table interest_group_links (interest_group_id uuid not null, type varchar(50) not null check ((type in ('WEBSITE','INSTAGRAM','FACEBOOK','TWITTER','LINKEDIN','YOUTUBE','TIKTOK'))), url varchar(2048) not null, primary key (interest_group_id, type, url));
create table interest_group_membership (joined_at timestamp(6), interest_group_id uuid not null, user_id uuid not null, role varchar(255) check ((role in ('ADMIN','MEMBER'))), status varchar(255) check ((status in ('ACCEPTED','PENDING','DENIED','WITHDREW','BANNED'))), primary key (interest_group_id, user_id));
create table interest_group_tags (interest_group_id uuid not null, tags varchar(100));
alter table if exists interest_group_links add constraint FK3519psi1d5n0prhs7ectxqyfy foreign key (interest_group_id) references interest_group;
alter table if exists interest_group_membership add constraint FK969x3gmh9kq16vevdr74h0t3g foreign key (interest_group_id) references interest_group;
alter table if exists interest_group_tags add constraint FKcbscsmlvmrmdqc0ih8c6dlgkk foreign key (interest_group_id) references interest_group;

create table events (deleted boolean not null, created_at timestamp(6), end_time timestamp(6), start_time timestamp(6), created_by uuid, id uuid not null, description varchar(255) not null, name varchar(255) not null, primary key (id));
comment on column events.deleted is 'Soft-delete indicator';
create table event_interest_groups (event_id uuid not null, event_interest_groups uuid);
create table event_participants (event_id uuid not null, user_id uuid not null, role varchar(255) check ((role in ('HOST','COHOST','GUEST'))), primary key (event_id, user_id));
create table event_tags (event_id uuid not null, tag varchar(100));
create table reservations (guests integer not null, event_id uuid not null, user_id uuid not null, payload varchar(255), status varchar(255) check ((status in ('PENDING','ACCEPTED','WHITELIST','DENIED','WITHDREW'))), primary key (event_id, user_id));
alter table if exists event_interest_groups add constraint FK9pyxt3n5c0gtivo6y3nxyw5fg foreign key (event_id) references events;
alter table if exists event_participants add constraint FK2x391urx4up03f4jp2y9mdt5x foreign key (event_id) references events;
alter table if exists event_tags add constraint FKiwoyitw224ykom58m5xnoa9y6 foreign key (event_id) references events;
alter table if exists reservations add constraint FKcnr8finplwp8whntrr02jpvre foreign key (event_id) references events;
